
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
server:
    port: 9400
    servlet:
        context-path: /whm
spring:
    application:
        name: whm
    datasource:
        url: jdbc:mysql://121.201.110.196:3306/whmdb
        password: Whmdb123
        username: whmdb
        driverClassName: com.mysql.jdbc.Driver
        jmx-enabled: true
        tomcat:
            initial-size: 1
            max-idle: 1
            max-wait: 10000
            min-idle: 1
            test-on-borrow: true
            test-while-idle: true
            time-between-eviction-runs-millis: 30000
            validation-query: SELECT 1 FROM DUAL
    mvc:
        static-path-pattern: /**
    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:E:/ws_szs/cms
    
    servlet:
        multipart:
            maxFileSize: 50Mb
            maxRequestSize: 50Mb
    security:
       user:
          name: whm
          password: whm
          roles: ROLE_ADMIN
      
com:
    crfsdi:
        weixin-api-url: https://api.weixin.qq.com/sns/jscode2session?appid={APPID}&secret={SECRET}&js_code={JSCODE}&grant_type=authorization_code
        weixin-appid: wx9d2fed9eddc822e0
        weixin-secret: 23795b455aa61d54a18c0251271d3460
        
        